version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # build the application image
      - run: docker build -t sriv1211/three-tier .

      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      # deploy the image
      - run: docker push sriv1211/three-tier